RCS Build Aid Changelog
=======================
Elián Hanisch <lambdae2@gmail.com>
v0.4.6, April 2014:

This document lists important changes between versions.

Version 0.4.6
-------------
*Release date: 17/04/2014*

* FIX: RCS dV reading not showing in 0.23.5
* FIX: new massless parts weren't recognized as such.
* Marker scaling for the CoT and CoL markers.

Version 0.4.5
-------------
*Release date: 14/03/2014*

* The circular arrow now is proportional to the expected angular acceleration
  instead of torque.
* The coordinate system is now referenced to the vessel.
* Use Windows line endings in text files, so Windows users doesn't have to ditch
  their beloved notepad (source files unchanged).
* Workaround for engines of outdated mods.

Version 0.4.4
-------------
*Release date: 18/01/2014*

* ACoM marker, average center of mass.
* Support for engines using ModuleEnginesFX.
* Pick extra RCS parameters that mods might make tweakables.
* Reverted change that made arrows solid.

Version 0.4.3
-------------
*Release date: 06/01/2014*

* Support for blizzy78's toolbar.
* Hide dV readout when it isn't accurate (like with modded RCS).
* FIX: torque calculation in rotation mode wasn't correct.

Version 0.4.2
-------------
*Release date: 01/01/2014*

* RAPIER support.
* Delta V and burn time readout for RCS (because I could).
* TWR readout for engines.
* Added slider for change the scale of CoM markers.
* Set to ignore all ladders as they incorrectly show mass in the editor, much
  like landing gears.

Version 0.4.1
-------------
*Release date: 24/12/13*

* KSP 0.23 fixes.
* Account tweakables in fuel tanks and engines.
* Ignore the mass of landing gear and launch clamps, in both DCoM and CoM.
* Dynamic list of resources in mass window.

Version 0.4
-----------
*Release date: 19/10/13*

* GUI added.
* Show magnitudes of torque, translation and other information.
* Some resource options for DCoM marker.
* Option for hide CoM/DCoM markers.
* Removed M and P keybinds.
* FIX: translation keybindings should match the correct direction in VAB.
  (they won't match in SPH)
* FIX: the plugin could cause important fps drops while in VAB/SPH.

Version 0.3.2
-------------
*Release date: 30/08/2013*

* Basic engine support, enable with the P key.
* Use translation keybindings from game settings (M and P keys are still
  hardcoded).

Version 0.3.1
-------------
*Release date: 07/08/2013*

* FIX: DCoM disabled permanently after deactivating CoM.

Version 0.3
-----------
*Release date: 06/08/2013*

* Dry Center of Mass (DCoM).
* Better torque indicator.
* Don't scale CoM markers.
* Warning message for when there are no RCS thrusters.

Version 0.2
-----------
*Release date: 24/06/2013*

* An indication to where your translation or torque vector should be
  pointing.
* Rotation mode, for balance rotation.
* Don't use the space bar anymore, but the `hnjkli` keys.
* FIX: Occasional doubling or disappearance of arrows.
* FIX: Incorrect placement of RCS forces (Evident in mods such as B9).
* FIX: Forces changing magnitude while dragging the vehicle.
* FIX: Do not calculate forces with disconnected parts.

Version 0.1
-----------
*Release date: 15/06/2013*

* Initial release.
