RCS Build Aid Plugin
====================
Elián Hanisch <lambdae2@gmail.com>
v0.4.2, December 2013:

Aid tool for balancing RCS thrusters around the center of mass while building a
rocket, and a bit more.

Requirements
------------

KSP version 0.23

Installation
------------

Just copy RCSBuildAid directory into your KSP's GameData directory. The
path should be `KSP_path/GameData/RCSBuildAid/Plugins/RCSBuildAid.dll`

Features
--------

* Configurable dry center of mass marker.
* Display of translation and torque forces due to RCS thrusters.
* Display of torque forces due to engines.
* Delta V readout for RCS.

Usage
-----

While in VAB (Vehicular Assembly Building) or in SPH (Space Plane Hangar) turn 
on the Center of Mass (CoM) marker. You should see the RCS Build Aid window and
an extra red marker close to the CoM marker, this is the Dry Center of Mass
(DCoM) marker.

For disable everything just turn off the CoM marker.

Forces
~~~~~~

The forces displayed are of 3 types:

Part forces::
Forces exerted by parts, they are colored cyan for RCS and yellow for engines.

Translation force or thrust::
Colored in green, represents the translation motion of your vessel, essentially 
your vessel's thrust. A green marker near the tip of the arrow indicates  where
it should be pointing ideally.

Torque force::
Colored in red, represents the resulting torque the thrusters are exerting into
your vessel. When you see a red arrow, it means at in the current configuration
and with the given input your vessel will rotate. However, depending of your
vessel's mass, this rotation might not be noticeable (the higher the mass, the
harder to turn). Like in the translation force, a red marker in the arrow's tip
would be indicating the ideal direction.

Markers
~~~~~~~

CoM::
The Center of Mass marker, colored yellow. You should be familiar with this one.

DCoM::
The Dry Center of Mass marker, colored red, indicates the center of mass for
your vessel without resources.

All forces are referenced to either the CoM or DCoM markers, you select which
one from the GUI. Checking how forces change depending of where your CoM is will
help you to understand how to balance best your vessel, eg, for a vessel that
docks with almost no fuel it would be best to balance RCS around the DCoM and
ignore the CoM marker. If you want your vessel to be balanced in most situations
you need to build your vessel in a way that keeps both center of masses as close
as possible.

RCS mode
~~~~~~~~

This mode is for balancing RCS, enabled with the `RCS` button. It will show the
torque and translation forces of the installed RCS for the active direction. RCS
forces are represented by cyan vectors.

=== Switching direction

You can change direction from the GUI, or alternatively with the same keys for 
translating your vessel. If default game settings the keys are:

[horizontal]
H :: Set RCS forces to move forward.
N :: Set RCS forces to move backwards.
L :: Set RCS forces to translate right.
J :: Set RCS forces to translate left.
I :: Set RCS forces to translate down.
K :: Set RCS forces to translate up.

NOTE: Setting the same direction twice is a shortcut for disable RCS mode.

=== Balancing RCS

Having balanced RCS means that when you're translating your vessel won't rotate
and when you are rotating it won't translate, this is important for easy
docking. This depends of the position of your CoM and the placement of your
RCS thrusters.

From the GUI you can select to balance either translation or rotation.

==== Balancing translation

The RCS will attempt to translate your vessel to the given direction, with the
green arrow being the actual resulting motion. In this situation you want
translation motion without any rotation, so you want to place your RCS around
your CoM in a way that reduces the torque vector (red arrow) as much as
possible.

==== Balancing rotation

Is the same than translation except that here you want to reduce the translation
vector (green arrow) while keeping the torque vector aligned with the red
marker. In most vessels you won't need to do this since balanced translation
implies balanced rotation, but this is not always true.

Engine Mode
~~~~~~~~~~~

This mode is for engine balancing, enabled with the `Engines` button. The
engines used for calculating forces are always the engines in the bottommost
stage, if you want to disable some engines you can to move them to a higher
stage.

Markers
~~~~~~~

From the `Mass` tab can see some information about the markers and you can
show or hide either the CoM or DCoM markers. You can also select which type of
resource should be removed for the calculation of the DCoM. 

Incompatible plugins
--------------------

This plugin will work only with RCS thrusters that use the `ModuleRCS` module, 
and engines that use `ModuleEngines` or `MultiModeEngine` modules. Mods with
custom modules or that replace stock modules will not work or break this 
plugin.

*Plugins known to be incompatible*

* KerbCom Avionics

Known Issues
------------

* Delta V readout for RCS is very dumb regarding resources, it assumes 
MonoPropellant is the only fuel for all RCS thrusters. Attaching RCSs that 
use other resources (like ElectricCharge) will break the reading.

Reporting Bugs
--------------

You can report bugs or issues directly to GitHub:
https://github.com/m4v/RCSBuildAid/issues

Links
-----

Repository in GitHub:
https://github.com/m4v/RCSBuildAid

Forum thread:
http://forum.kerbalspaceprogram.com/showthread.php/35996

License
-------

This plugin is distributed under the terms of the LGPLv3.

---------------------------------------
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
---------------------------------------
